---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: barman
  state_top:
    base:
      '*':
        - barman

platforms:
  - name: ubuntu-xenial
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - barman
        barman.sls:
          barman:
            log_level: INFO
            compression: gzip

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE