---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: barman
  state_top:
    base:
      '*':
        - barman

platforms:
  - name: ubuntu-xenial
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - barman
        barman.sls:
          barman:
            log_level: INFO
            compression: gzip
            hosts:
              pgsql1:
                description: "Example of PostgreSQL Database (Streaming-Only)"
                conninfo: "host=pgsql1 user=barman dbname=postgres"
                backup_method: postgres
                streaming_conninfo: "host=pg user=streaming_barman"
                streaming_archiver: "on"
                slot_name: barman
                last_backup_maximum_age: "1 DAYS"
                retention_policy: REDUNDANCY 4
                cron:
                  ensure: present
                  hour: 23
                  minute: 30                
              pgsql2:
                description: "Example of PostgreSQL Database (via Ssh)"
                conninfo: "host=pgsql2 user=barman dbname=postgres"
                backup_method: "rsync"
                ssh_command: "ssh postgres@pgsql2"
                reuse_backup: link
                archiver: "on"
                last_backup_maximum_age: "1 DAYS"
                retention_policy: REDUNDANCY 4
                cron:
                  ensure: present
                  hour: 23
                  minute: 30                            

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE